version: '3.8'
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    tty: true
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    volumes:
      - ${NGINX_BASE_PATH}/data:/data
      - ${NGINX_BASE_PATH}/letsencrypt:/etc/letsencrypt

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    tty: true
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    name: nginx-proxy-network